name: Renovate
on: 
  workflow_dispatch:
  schedule:
    - cron: '15 15 * * *'
  push:
    branches:
      - main
    
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          configurationFile: config.json
          token: ${{ secrets.RENOVATE_TOKEN }}
          renovate-version: ${{ vars.RENOVATE_VERSION }}
        env:
          LOG_LEVEL: ${{ vars.RENOVATE_LOG_LEVEL }}
