name: Renovate
on: 
  workflow_dispatch:
  schedule:
    - cron: '15 15 * * *'
  push:
    branches:
      - main
    
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: renovate
        uses: renovatebot/github-action@v41.0.22
        with:
          configurationFile: config.json
          token: ${{ secrets.RENOVATE_TOKEN }}
          renovate-version: ${{ vars.RENOVATE_VERSION }}
        env:
          LOG_LEVEL: ${{ vars.RENOVATE_LOG_LEVEL }}
