name: Renovate
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0/1 * * *'
  push:
    branches:
      - main
    
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: renovate
        uses: renovatebot/github-action@v39.0.5
        with:
          useSlim: true
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: info
