name: Renovate
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0/1 * * *'
  push:
    branches:
      - main
    
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: renovate
        uses: renovatebot/github-action@v39.0.5
        with:
          useSlim: true
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: info
