name: Renovate
on: 
  workflow_dispatch:
  schedule:
    - cron: '15 15 * * *'
  push:
    branches:
      - main
    
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: renovate
        uses: renovatebot/github-action@v40.2.7
        with:
          configurationFile: config.json
          token: ${{ secrets.RENOVATE_TOKEN }}
          renovate-version: ${{ vars.RENOVATE_VERSION }}
        env:
          LOG_LEVEL: ${{ vars.RENOVATE_LOG_LEVEL }}
