name: Renovate
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0/1 * * *'
  push:
    branches:
      - main
    
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: renovate
        uses: renovatebot/github-action@v40.1.1
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
          renovate-version: 37.191.0
        env:
          LOG_LEVEL: ${{ vars.RENOVATE_LOG_LEVEL }}
