name: Renovate
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0/1 * * *'
  push:
    branches:
      - main
    
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.2
      - name: renovate
        uses: renovatebot/github-action@v38.1.2
        with:
          useSlim: true
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: info
