name: Renovate
on: 
  workflow_dispatch:
  schedule:
    - cron: '15 15 * * *'
  push:
    branches:
      - main
    
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: renovate
        uses: renovatebot/github-action@v40.3.2
        with:
          configurationFile: config.json
          token: ${{ secrets.RENOVATE_TOKEN }}
          renovate-version: ${{ vars.RENOVATE_VERSION }}
        env:
          LOG_LEVEL: ${{ vars.RENOVATE_LOG_LEVEL }}
